enum QueryKeys {
  GET_USER_BY_ID = "GET_USER_BY_ID",
  PERSON_SEARCH = "PERSON_SEARCH",
  DARK_DATA_KEYWORD_SEARCH = "DARK_DATA_KEYWORD_SEARCH",
  CITY_STATE_SEARCH = "CITY_STATE_SEARCH",
  GET_ACCESS_INFO = "GET_ACCESS_INFO",
  GET_NOTES = "GET_NOTES",
  PERSON_CRIMINAL_HISTORY = "PERSON_CRIMINAL_HISTORY",
  RECENTLY_VIEWED = "RECENTLY_VIEWED",
  ADDRESS_SUGGESTIONS = "ADDRESS_SUGGESTIONS",
  GET_ADDRESS_BY_MAP_ID = "GET_ADDRESS_BY_MAP_ID",
  ADDRESS_LOOKUP = "ADDRESS_LOOKUP",
  GET_GEO_DATA_FROM_ID_LIST = "GET_GEO_DATA_FROM_ID_LIST",
  GET_CASE_NUMBER_LIST = "GET_CASE_NUMBER_LIST",
}

export default QueryKeys;
